-- MySQL Script generated by MySQL Workbench
-- Wed May 29 10:53:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projeto_adulao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_adulao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_adulao` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_swedish_ci ;
USE `projeto_adulao` ;

-- -----------------------------------------------------
-- Table `projeto_adulao`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_adulao`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(220) NOT NULL,
  `type` TINYINT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_swedish_ci;


-- -----------------------------------------------------
-- Table `projeto_adulao`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_adulao`.`persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(220) NOT NULL,
  `last_name` VARCHAR(220) NOT NULL,
  `birthday` DATE NOT NULL,
  `civil_status` TINYINT NOT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `education` TINYINT NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_persons_roles1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_persons_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `projeto_adulao`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_swedish_ci;


-- -----------------------------------------------------
-- Table `projeto_adulao`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_adulao`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(220) NOT NULL,
  `initial_date` DATE NOT NULL,
  `final_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `duration` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activities_persons1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_activities_persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `projeto_adulao`.`persons` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_swedish_ci;


-- -----------------------------------------------------
-- Table `projeto_adulao`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_adulao`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(220) NOT NULL,
  `email` VARCHAR(220) NOT NULL,
  `password` VARCHAR(180) NOT NULL,
  `password_reset_token` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
